seed: 42
exp_name: "my_experiment"
wandb_project_name: "aaas_project"
wandb_entity: "aarcara"
video_dir: "./videos"
video_interval: 1000
env_config:
  num_envs: 128
  layouts:
    - "cramped_room"
  info_level: 0
  horizon: 400
training_config:
  num_steps: 10000
  total_updates: 50_000_000
  gae_lambda: 0.95
  gae_gamma: 0.99
  update_epochs: 15
  minibatch_size: 8192
  learning_rate: 2.5e-4
  value_coef: 0.5