seed: 42
exp_name: best_experiment_with_reward_annealing 
wandb_project_name: aaas_project
wandb_entity: aarcara
eval_interval: 50
video_dir: ./videos/
checkpoint_dir: ./checkpoints/
env_config:
  num_envs: 15
  layouts:
    - cramped_room
    - asymmetric_advantages
    - coordination_ring
    - counter_circuit
    - forced_coordination
  info_level: 0
  encoding: featurized 
  horizon: 400
  shaping_mode: shared 
  reward_annealing_steps: 5_000_000
training_config:
  num_steps: 800
  update_epochs: 10
  total_updates: 10_000_000
  gae_lambda: 0.94
  gae_gamma: 0.99
  minibatch_size: 4000 
  learning_rate: 4.5e-4
  value_coef: 0.5
  entropy_coef: 0.0135
  ppo_epsilon: 0.2
  adam_epsilon: 1e-5
  adam_momentum: 0.9
  max_grad_norm: 0.5
  use_learning_rate_annealing: true
  use_advantage_normalization: true
  use_gradient_clipping: true
  use_parameter_sharing: true
  network:
    type: mlp
    shared_backbone: false
    hidden_dim: 256
    embedding_dim: 64